- import_tasks: kubernetes_user_exists.yml
  tags: users
- import_tasks: docker_installed.yml
  tags: docker
- import_tasks: k8s_bins_installed.yml
  tags: bins
- import_tasks: cni_bins_installed.yml
  tags: bins
- import_tasks: certs_and_keys_installed.yml
  tags: pki
- import_tasks: kubeconfigs_generated.yml
  tags: kubeconfigs
- import_tasks: kubelet_started.yml
  tags: services
- import_tasks: kube_proxy_started.yml
  tags: services
