pki__pki_dir: /etc/kubernetes/pki
pki__elliptic_curve_type: secp384r1
pki__etcd_ca_cert_valid_days: 5475
pki__k8s_ca_cert_valid_days: 5475
pki__k8s_front_proxy_ca_cert_valid_days: 5475
pki__kube_apiserver_server_cert_valid_days: 5475
pki__kube_controller_manager_server_cert_valid_days: 5475
pki__kube_scheduler_server_cert_valid_days: 5475
pki__kube_apiserver_to_kubelet_client_cert_valid_days: 5475
pki__admin_client_cert_valid_days: 5475
pki__kube_controller_manager_client_cert_valid_days: 5475
pki__kube_scheduler_client_cert_valid_days: 5475
pki__cloud_controller_manager_client_cert_valid_days: 5475
pki__kube_proxy_client_cert_valid_days: 5475
pki__kube_apiserver_to_etcd_client_cert_valid_days: 5475
pki__front_proxy_client_cert_valid_days: 5475
pki__etcd_server_cert_valid_days: 5475
pki__etcd_peer_server_cert_valid_days: 5475
pki__kubelet_server_cert_valid_days: 5475
