dev_env__stern_ver: 1.22.0
dev_env__stern_download_url: https://github.com/stern/stern/releases/download/v{{ dev_env__stern_ver }}/stern_{{ dev_env__stern_ver }}_linux_amd64.tar.gz
dev_env__stern_checksum: sha1:a43beb4763af0b34b1e588d860c5cb7ef63ea316

dev_env__jq_ver: 1.6
dev_env__jq_download_url: https://github.com/stedolan/jq/releases/download/jq-{{ dev_env__jq_ver }}/jq-linux64
dev_env__jq_checksum: sha1:056ba5d6bbc617c29d37158ce11fd5a443093949

dev_env__yum_repos_to_disable: '{{ base__yum_repos_to_disable }}'
dev_env__yum_pkgs_to_install:
- bind-utils
- nmap
- vim
- yum-utils
- tcpdump
- unzip
- git
- bash-completion
